# Flexget (http://www.flexget.com) configuration file.
#
# Created by: Jeff Wilson <jeff@jeffalwilson.com>
#

presets:
  global:
    include: [ private/global.yml ]
    # Make there's 50GB free before adding more downloads
    free_space:
      path: /raid
      space: 50000
    # Make sure all filenames are Windows safe (for samba)
    pathscrub: windows
    # Most of these are the results of problem torrents I kept seeing still pop up, so I wholesale blocked them
    # RegExr (http://www.gskinner.com/RegExr/) is a great tool for testing regexes
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}                    # Block any subbed/dubbed/etc videos
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} # Block series, only accept one at a time
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bR5\b: {from: title}                               # The following are poor quality types that somehow got through the quality
        - \bWEBSCR\b: {from: title}                           # features usually due to the title including a keyword like "720p" as well
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}                              # The following are groups with poor quality releases
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \[facepalm\]: {from: title}
        - \bASAP\b: {from: title}
    cookies: /home/deluge/.flexget/private/cookies.sqlite # Demonoid is a cookie monster (OM NOM NOM!)
    torrent_alive: 20 # Require at least 20 seeds of any torrent
    # Filter by filenames. Allow multiple video types and rar packs (but note if there is just a
    # single .rar file it won't be accepted)
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
        - '*.r0*'
        - '*.part0*'
      reject: [ 'password.txt' ]
    # Limit the frequency of requests to domains so they don't complain about using a bot
    domain_delay:
      bt-chat.com: 5 seconds
      torrentz.eu: 5 seconds
    email:
      from: deluge@Faraday.singularity.net
      to: atlanta800+flexget@gmail.com
    # Deluge is configured in my private configs, but I'm leaving this for clarity and completeness
    #deluge:
    # # Ignore all but the file that is >90% of the torrent if it exists
    # # Yor will most likely want to combine this with the 'DeletePartials' Deluge plugin
    #  main_file_only: yes

  # This preset is a "global" preset for all TV-related feeds.
  # We keep all of the RSS feeds that list tv-related torrents here
  # as well as where to check existing shows.
  tv-global:
    include: [ private/tv-global.yml ]
    # This is a TON of feeds, you probably don't need so many, but why not?
    inputs:
      #- rss: { url: 'http://static.demonoid.me/rss/3.xml', silent: yes }        # Demonoid (All TV)
      - rss: { url: 'http://www.torlock.com/television/rss.xml', silent: yes }  # TorLock (TV)
      - rss: { url: 'http://torrentz.eu/feed_verified?q=tv', silent: yes }      # Torrentz (Verified only, TV)
      - rss: { url: 'http://ezrss.it/feed/', silent: yes }                      # EZRSS
      - rss: { url: 'http://showrss.karmorra.info/feeds/all.rss', silent: yes } # Karmorra (All)
      - rss: { url: 'http://rss.bt-chat.com/?group=3', silent: yes }            # BT-Chat (EZTV)
      - rss: { url: 'http://rss.thepiratebay.org/208', silent: yes }            # The Pirate Bay (Highres - TV shows)
    # Impose reasonable size constraints
    content_size:
      max: 4000
      min: 20
    # Prevent from downloading shows that were aquired manually
    # or are currently downloading
    exists_series:
      - "/raid/videos/TV Shows/"
      - "/raid/downloads/TV Shows/"
      - "/home/deluge/downloads/"
    # Look up info on TheTVDB.com to fill in extra info
    thetvdb_lookup: yes
    # Add accepted entries to Deluge and make sure they end up in the correct folder with a nice name
    set:
      # Rename the "content file" to something nice
      content_filename: >
        {{ series_name|replace('/', '_')|replace(':', ' -') }} - {% if series_id_type == 'ep' and thetvdb_lookup_season_offset|default(False) %}{{ "S%0.2dE%0.2d"|format((series_season + thetvdb_lookup_season_offset),series_episode) }}{% else %}{{ series_id }}{% endif %}{% if ep_name|default(False) %} - {{ ep_name|replace('/', '_')|replace(':', ' -') }}{% endif %} - {{ quality }}
      label: tv

  # These are the shows I regularly watch
  tv-my_shows:
    # I've broken out my series lists into a seperate yml to clean up my config
    include: [ series.yml ]
    # Add accepted entries to Deluge, queue them to the top and make sure they end up in the
    # correct folder
    set:
      movedone: >
        /raid/videos/TV Shows/{{ series_name|replace('/', '_')|replace(':', ' -') }}/{% if series_id_type == 'ep' %}Season {{ series_season +  thetvdb_lookup_season_offset|default(0)}}/{% endif %}
      queuetotop: yes
    # This is a custom plugin, it is part of my rar-unpacking method, it changes 'movedone'
    # based on the regexp in the key
    content_sort:
      '*.rar': '/home/deluge/downloads/completed/tv_shows/'

  # I'm always up for new shows, but some I genres I just can't stand. This preset
  # grabs all of the premieres except for some genres
  tv-premieres:
    # The entry has to have the series_genres field so I can filter by it
    require_field:
      - series_genres
      - ep_air_date
    # Block these genres if they exist in the list of series_genres at all
    regexp:
      reject:
        - documentary: {from: series_genres}
        - talk show: {from: series_genres}
        - game show: {from: series_genres}
        - reality: {from: series_genres}
        - children: {from: series_genres}
        - home and garden: {from: series_genres}
    if:
      # Block these genres only if they are the ONLY genre listed in series_genres
      # For example, this will not block a show that's both "Comedy" and "Drama" but it will
      # block a show that is just "Drama"
      - "series_genres == ['Drama']": reject
      # Block premieres that weren't within the last 60 days
      - ep_air_date != None and ep_air_date < now - timedelta(days=60): reject
    # Accept all series permieres, 1080p first, then minimum of 720p after 8 hours
    series_premiere:
      quality: 720p+ hdtv+ !10bit
      timeframe: 8 hours
    # Add to deluge, but don't queue to top (My_TV_Shows are more important) and put in a different
    # location
    set:
      movedone: "/raid/downloads/TV Shows/{{ series_name|replace('/', '_')|replace(':', ' -') }}/Season {{ series_season }}"
      queuetotop: no
      label: tv-premiere
    # This is a custom plugin, it is part of my rar-unpacking method, it changes 'movedone'
    # based on the regexp in the key
    content_sort:
      '*.rar': '/home/deluge/downloads/completed/tv_premieres/'

  # If a premier was grabbed, keep on tracking it until the directory is (re)moved
  tv-premieres-track:
    import_series:
      settings:
        quality: 720p+ hdtv+ !10bit
        timeframe: 8 hours
      from:
        listdir:
          - "/raid/downloads/TV Shows/"
    set:
      movedone: >
        /raid/downloads/TV Shows/{{ series_name|replace('/', '_')|replace(':', ' -') }}/{% if series_id_type == 'ep' %}Season {{ series_season +  thetvdb_lookup_season_offset|default(0)}}/{% endif %}
      queuetotop: no
      label: tv-premiere-track
    # This is a custom plugin, it is part of my rar-unpacking method, it changes 'movedone'
    # based on the regexp in the key
    content_sort:
      '*.rar': '/home/deluge/downloads/completed/tv_premieres/'

  # This preset is a "global" preset for all movie-related feeds.
  # We keep all of the RSS feeds that list movie-related torrents here
  # as well as some other configurations.
  movies-global:
    include: [ private/movies-global.yml ]
    inputs:
      #- rss: { url: 'http://static.demonoid.me/rss/1.xml', silent: yes }       # Demonoid (All Movies)
      - rss: { url: 'http://www.torlock.com/movies/rss.xml', silent: yes }     # TorLock (Movies)
      - rss: { url: 'http://torrentz.eu/feed_verified?q=movies', silent: yes } # Torrentz (Verified Movies)
      - rss: { url: 'http://rss.thepiratebay.org/207', silent: yes }           # The Pirate Bay (Highres - Movies)
    # Some feeds might include TV Shows, ignore them
    regexp:
      reject:
        - s\d+e\d+: {from: title}
        - '\d{4}.\d{2}.\d{2}': {from: title}
        - \d+x\d+: {from: title}
    # Force proper_movies to run after regexp to avoid unnecessary imdb_lookup
    plugin_priority:
      if: 173
      proper_movies: 171
    # Impose reasonable size constraints
    content_size:
      max: 16000
      min: 1000
    imdb_lookup: yes
    rottentomatoes_lookup: yes
    seen_movies: strict # Don't download movies we've already seen
    # Check for already downloaded or currently downloading movies
    exists_movie:
      - /raid/videos/Movies/
      - /raid/videos/SDMovies/
      - /raid/downloads/Movies/
      - /home/deluge/downloads/
    # Download propers, since they will have the same content_filename, lower/non propers will be overwritten
    proper_movies: yes
    set:
      # Give folders/files nice names
      movedone: "/raid/downloads/Movies/{{ imdb_name|replace('/', '_')|replace(':', ' -') }} ({{ imdb_year }})"
      content_filename: |
        {{ imdb_name|replace('/', '_')|replace(':', ' -') }} ({{ imdb_year }}) - {{ quality }}
    # This is a custom plugin, it is part of my rar-unpacking method, it changes 'movedone'
    # based on the regexp in the key
    content_sort:
      '*.rar': '/home/deluge/downloads/completed/movies/'
 
  # This preset runs feeds through my very specific custom filter
  movies-auto:
    quality: 720p+ bluray !10bit
    my_movie_filter: yes
    set:
      queuetotop: no

  # This preset uses the movie queue to download movies
  movies-queued:
    movie_queue: yes
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - flexget_archive: yes
        - torrentz
        - demonoid: movies
        - piratebay
      type: movies
    set:
      label: my-movies

# This is where we pull everything together
feeds:

  # Use a local folder (synced with Dropbox) to use as a source in other feeds
  Local_Torrents-TV:
    priority: 1
    preset:
      - tv-global
      - tv-my_shows
    disable_plugin:
      - inputs
      - exists_series
      - regexp
      - content_size
      - torrent_alive
    listdir: /home/atlanta800/Dropbox/torrents/TV
    accept_all: yes


  Local_Torrents-Movies:
    priority: 2
    preset:
      - movies-global
    disable_plugin:
      - inputs
      - exists_movies
      - regexp
      - content_size
      - torrent_alive
    listdir: /home/atlanta800/Dropbox/torrents/Movies
    accept_all: yes

  # All of the TV-related feeds pull in the tv-global preset, this gives
  # all of the necessary rss sources and a few extra configs

  # There are 3 My_TV Shows feeds, the first, tries to get the most wanted qualities
  My_TV_Shows:
    priority: 10
    preset:
      - tv-global
      - tv-my_shows
    series:
      settings:
        Best: { quality: 720p+ hdtv+ !10bit }
        Better: { quality: 720p+ dvdscr+ !10bit }
        Average: { quality: webrip+ !10bit }

  # If we can't find anything that good after 12 hours, fall back to a lower quality
  My_TV_Shows-Secondary:
    priority: 20
    preset:
      - tv-global
      - tv-my_shows
    series:
      settings:
        Best: { quality: 720p+ dvdscr+ !10bit }
        Better: { quality: hdtv+ !10bit }
        Average: { quality: tvrip+ !10bit }
    delay: 12 hours

  # If we can't find anything better after 3 days, screw it, just get it
  # Do note that the other 2 feeds still run before this one, so we can still
  # get a good quality torrent if it shows up
  My_TV_Shows-Fallback:
    priority: 30
    preset:
      - tv-global
      - tv-my_shows
    series:
      settings:
        Best: { quality: hdtv+ !10bit }
        Better: { quality: tvrip+ !10bit }
        Average: { quality: preair+ !10bit }
    delay: 3 days

  # Feed for the tv-premieres plugin
  Series_Premieres:
    priority: 40
    preset:
      - tv-global
      - tv-premieres

  # Feed for the tv-premieres-track plugin
  Series_Premieres_Track:
    priority: 50
    preset:
      - tv-global
      - tv-premieres-track

  # This feed queues all of the movies in my IMDB watchlist
  IMDB_Movie_Queue:
    priority: 100 # Always run before My_Movies feeds
    preset: no_global # None of the global presets make sense here
    interval: 2 hours # Only check every 2 hours (I have Flexget run every hour)
    imdb_list:
      user_id: ur7174817
      list: watchlist
    accept_all: yes
    queue_movies: # Output entries to movie queue (with any quality)
      force: no
  
  # The next two feeds download the queue from the previous feed effectively implementing
  # a 2 day timeframe for 1080p movies, then falls back to 720p
  My_Movies-1080p:
    priority: 110
    preset:
      - movies-global
      - movies-queued
    quality: 1080p bluray h264 !mp3

  My_Movies-720p:
    priority: 120
    preset:
      - movies-global
      - movies-queued
    quality: 720p+ bluray xvid-h264 !mp3
    delay: 2 days # Wait 2 days for a 1080p movie before trying downloading 720p

  # This feed simply implements the movies-auto preset
  Auto_Movies:
    priority: 130
    preset:
      - movies-global
      - movies-auto
    set:
      label: movies-auto

  # This feed discovers movies from Rotten Tomatoes and searches for them
  Discovered_Movies:
    priority: 140
    interval: 24 hours # Only once every day (I have Flexget run every hour)
    preset:
      - movies-global
      - movies-auto
    disable_plugin: inputs
    discover:
      what:
        - rottentomatoes_list:
            dvds:
              - top_rentals
              - new_releases
      from:
        - flexget_archive: yes
        - torrentz
        #- demonoid: movies
        - piratebay
      type: movies
    set:
      label: movies-discovered

